### ISSUE TITLE
problem with HEALTHCHECK in docker swarm mode

### ISSUE THREAD

**Issue by ChrisBarriere** [opendatateam/docker-elasticsearch#1]
This Dockerfile use elasticsearch:2.4.5-alpine

But in alpine "curl package" is not installed.

So the process exit on each healthcheck and the container restart indefinitely

Three solutions:
- change the FROM for base image with curl
- make the healthcheck with wget in teh Dockerfile
- install curl package in the Dockerfile

**Comment by abulte** [comment]
Fixed by #2
